### PR TITLE
updates to KK: made back in Mar

### PR DESCRIPTION
**Pull request by tianranc**
These changes/installations were made in order to run KK.

### CODE REVIEW

**Review by egull — CHANGES_REQUESTED** [review]
Hey Tianran,

you've checked in a whole bunch of stuff that should not be in the repo. For instance, you've added all of the contents of CMakeFiles in kk, or even the kk executable itself.  Those should not be in the repository because they are automatically generated. Instead, you should add only line 5 in CMakeLists.txt, which has the find_package(GSL) line... that's a change that's needed. Please remove the rest.

**Comment by egull** [comment]
oh, in fact the commit 3a9e24c has the binary information that shouldn't be in the repo. The commit 
6ce890c  has the important change. So all you need to do is remove commit 3a9e24c and the changes will be fine.

**Comment by tianranc** [comment]
Ok I will remove. Basically the only change is one line in the CMakeLists.txt, right?

**Comment by egull** [comment]
that’s right.

**Comment by tianranc** [comment]
commit 3a9e24c is now removed.

**Review by egull — APPROVED** [review]
Thanks a lot!

**Pull request merged**
